### ISSUE TITLE
[Errno 111] Connection refused. Is adb running on your computer?

### ISSUE THREAD

**Issue by bsrdjan** [hassio-addons/addon-adb#28]
# Problem

I have two Amazon Fire TV sticks connected via wired LAN to FritzBox router. To connect them with HA, I installed and configured the ADB. The `media_server` entities are not showing, despite ADB shows the status `connected`. The ADB debugging is enabled on Fire-TV sticks and HA RSA key permanent accepted.

## Steps to reproduce

HA restart:

**configuration.yaml**

```yaml
media_player:
  - platform: androidtv
    name: ATV1
    host: 192.168.178.12
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    exclude_unnamed_apps: true

  - platform: androidtv
    name: ATV2
    host: 192.168.178.13
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    exclude_unnamed_apps: true
```

**ADB configuration**

<img width="346" alt="Screenshot 2020-11-23 at 14 05 52" src="https://user-images.githubusercontent.com/1697847/99965393-1758ba80-2d95-11eb-8d06-b87e2e74269a.png">

**ADB log**

```shell
ADB - Android Debug Bridge
-----------------------------------------------------------
 Hass.io Add-on: ADB - Android Debug Bridge
 The Android Debug Bridge server program
-----------------------------------------------------------
 Add-on version: 0.6.3
 You are running the latest version of this add-on.
 System: HassOS 4.17  (amd64 / intel-nuc)
 Home Assistant Core: 0.118.2
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adb.sh: executing... 
[cont-init.d] adb.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:56:28] INFO: Starting the Android Debug Bridge server...
[12:56:29] INFO: Connecting to device: 192.168.178.12...
connected to 192.168.178.12:5555
[12:56:29] INFO: Connecting to device: 192.168.178.13...
connected to 192.168.178.13:5555
```

**HA log**

```shell
Logger: homeassistant.components.androidtv.media_player
Source: components/androidtv/media_player.py:227
Integration: androidtv (documentation, issues)
First occurred: 1:53:54 PM (2 occurrences)
Last logged: 1:53:54 PM

Could not connect to ATV1 at 192.168.178.12:5555 using ADB server at 127.0.0.1:5037
Could not connect to ATV2 at 192.168.178.13:5555 using ADB server at 127.0.0.1:5037

Logger: androidtv.adb_manager.adb_manager_async
Source: /usr/local/lib/python3.8/site-packages/androidtv/adb_manager/adb_manager_async.py:410
First occurred: 1:53:54 PM (2 occurrences)
Last logged: 1:53:54 PM

Couldn't connect to 192.168.178.12:5555 via ADB server 127.0.0.1:5037, error: ERROR: connecting to 127.0.0.1:5037 [Errno 111] Connection refused. Is adb running on your computer?
Couldn't connect to 192.168.178.13:5555 via ADB server 127.0.0.1:5037, error: ERROR: connecting to 127.0.0.1:5037 [Errno 111] Connection refused. Is adb running on your computer?
```
Is this a bug or a gap in my configuration?
